inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    # there is no reason to test external files
    - "vendor/**/*"
    - "packer-templates/**/*"
  # enable detailed explanations available in cops
  # the default output is not enough to understand what is wrong
  DisplayCopNames: true
  ExtraDetails: true
  DisplayStyleGuide: true

  # the default CacheRootDirectory is no longer `/tmp`, but a directory under
  # `$HOME` and some Unix platforms use symlink to that path
  AllowSymlinksInCacheRootDirectory: true

Style/StringLiterals:
  # prefer double quotes
  EnforcedStyle: double_quotes

Style/SymbolArray:
  # prefer brackets for `grep-ability`
  EnforcedStyle: brackets

Metrics/BlockLength:
  Exclude:
    # Vagrantfile is not application code, rather, configuration file and
    # blocks in it tends to be long
    - "**/Vagrantfile"
  ExcludedMethods:
    # these two exclude long blocks in `_spec.rb`
    - describe
    - context
    # this exclude long namespace in Rakefile
    - namespace

Metrics/LineLength:
  Exclude:
    # same as in Metrics/BlockLength
    - "**/Vagrantfile"
    # Gemfile is not application code
    - "Gemfile"
  # ignore heredoc for readability
  AllowHeredoc: true
  # URLs are almost always long
  AllowURI: true
  URISchemes:
    - http
    - https
    - git
    - ftp
  IgnoreCopDirectives: true
