---
name: Run rubocop
on:
  - pull_request
  - push

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup ruby
        uses: actions/setup-ruby@v1

      - name: Install bundler
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Run rubocop target
        run: |
          bundle exec rake test:rubocop
